### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by hishamco** [aspnet/RazorPages#27]
Does localization will be supported via ```IViewLocalizer``` or we will use it as injected service **Localizer** such as **Logger** for simplicity

**Comment by DamianEdwards** [comment]
You'll import it yourself just like today I think, i.e. `@inject IViewLocalizer Localizer` or `@inject IStringLocalizer<SomeType> Localizer`

**Comment by hishamco** [comment]
I know that, but I thought may we can inject it such as ```Logger```

**Comment by DamianEdwards** [comment]
The difference is that with `ILogger<T>` you can't actually declare it at all because you don't know the generated page class name. `IViewLocalizer` was created to solve this exact problem. We could've solved this with something like `IViewLogger` that you elect to inject yourself, and maybe that's something we can look at.

**Comment by hishamco** [comment]
May aim to provide such a built-in helper that provide Localizer instead of DRY in every project
Thanks
