### ISSUE TITLE
Test performance of startup and editing with 1000 pages

### ISSUE THREAD

**Issue by rynowak** [aspnet/RazorPages#43]

**Comment by pranavkm** [comment]
For a 1000 pages, parsing and building the ActionDescriptors \ Route Table takes about 2.5 seconds at startup, serving the page takes about 4.5 seconds. Any changes after takes about ~2 seconds to rebuild the route table and 2.2 seconds to serve. 

There's plenty of room for improvements here since 

* We parse the page in entirety now.
* We have no caching for unchanged pages.

If we're restrictive about where the `pages` directive can be located (limit it to the first line of the page?), we can do significantly less work to solve the first concern. Caching would be trivial to add here.

**Comment by pranavkm** [comment]
Tracking for the second item: https://github.com/aspnet/RazorPages/issues/46.
